### ISSUE TITLE
Проблема синхронизации учетной записи

### ISSUE THREAD

**Issue by denis86111** [G-On-dev/homebridge-g-on-alice#1]
Отличный плагин! Спасибо! Только у меня проблема, в яндексе нет производителя g-on homebridge. Удачи вам в развитии!
![21E25948-5ECC-4086-A894-3756370983F0](https://user-images.githubusercontent.com/48566084/60570938-42df9d00-9d7b-11e9-89e0-b1c05767de70.png)

**Comment by Ziracul** [comment]
Плагин может и хороший, но не работает, контактов нет, на почту не отвечают. Надеюсь все таки ответят

**Comment by oleg77s** [comment]
Появился в списке...

**Comment by denis86111** [comment]
Увидел. Сколько стоит подписка?

**Comment by Ziracul** [comment]
А толку не работает

> Появился в списке...

**Comment by G-On-dev** [comment]
> А толку не работает
> 
> > Появился в списке...

Добрый день!
напишите нам на info@g-on.io. Мы поможем вам, чтобы плагин заработал.


> Увидел. Сколько стоит подписка?

Сейчас плагин работает бесплатно. Мы бы хотели ввести монетизацию в будущем. Сейчас мы собираем обратную связь. Напишите нам на почту info@g-on.io
