### ISSUE TITLE
Плагин возвращает аксессуары в Homebridge но в Яндекс они не залетают

### ISSUE THREAD

**Issue by AlexeyOblov** [G-On-dev/homebridge-g-on-alice#11]
Первый раз подключились нормально. Позже мне пришлось сбросить кэш всех аксессуаров в HB. После этого связь с ними в Яндексе пропала. Отвязал G-on, привязал снова. При попытке обновить устройства пишет : Не получилось обновить список устройств. Подождите немного и попробуйте еще раз.

**Comment by kot-925** [comment]
Попробуй по очереди отключать плагины (возможно какой-то конфликт), у меня была похожая ситуация, только случилось после обновления. Пришлось два плагина отключить, иначе не видел новые устройства

**Comment by vitaliy-kozlov** [comment]
Таже проблема, перепробовал все. Устройства недоступны пишет  ERROR: No connection to homebridge.g-on.io. Retrying... please review the README and the Homebridge configuration

**Comment by vitaliy-kozlov** [comment]
Кстати вероятнее всего проблема в том что в Homebridge добавлен ТВ аксессуар.

**Comment by AlexeyOblov** [comment]
> Кстати вероятнее всего проблема в том что в Homebridge добавлен ТВ аксессуар.
Точно. Удалил ТВ, все заработало

**Comment by AlexeyOblov** [comment]
Перед обновлением удалить ТВ, после обновления добавить ТВ обратно
