### ISSUE TITLE
Не привязывается аккаунт к Умному дому Яндекс

### ISSUE THREAD

**Issue by EvgAlex** [G-On-dev/homebridge-g-on-alice#14]
В процессе привязки, когда открывается сайт g-on идет бесконечное обновление страница, остановить никак нельзя. Как привязаться то к аккаунту?

**Comment by kot-925** [comment]
Такая же ерунда, неделю назад перестало работать, смотрю аккаунт отвязался, пытаюсь привязать ничего не получается

**Comment by RFG-G** [comment]
> В процессе привязки, когда открывается сайт g-on идет бесконечное обновление страница, остановить никак нельзя. Как привязаться то к аккаунту?

Исправлено.
