### ISSUE TITLE
[G-On Alice] error with action JSON data Cannot read properties of undefined (reading 'url')

### ISSUE THREAD

**Issue by shalasashka** [G-On-dev/homebridge-g-on-alice#16]
При попытке отправить команду c любого аксессуара в Яндексе, Homebridge показывает ошибку:
> [G-On Alice] error with action JSON data Cannot read properties of undefined (reading 'url')

Синхронизация с сервером работает:
- Статус контроллера: Онлайн
- Аксессуары видны в Умном Доме Яндекса
- В HomeKit все срабатывает

В конфиге сервере прописан `pin` и включен `debug`.
Сервер на `Ubuntu 22.04.1 LTS`, `Homebridge v1.6.0`, `Node.js v18.12.1`. Кроме Алисы, установлен `homebridge-config-ui-x`, `homebridge-broadlink-rm-pro` и `homebridge-z2m`.

Что делать?)

**Comment by sklvpvl** [comment]
Аналогичная проблема. Есть решение?

**Comment by andreyxc** [comment]
Node red + https://flows.nodered.org/node/node-red-contrib-alice = работает больше года , ни одной проблемы не было !
Все четко

**Comment by sklvpvl** [comment]
> Node red + https://flows.nodered.org/node/node-red-contrib-alice = работает больше года , ни одной проблемы не было ! Все четко

Спасибо, настроил

**Comment by dobriybober** [comment]
Тоже все активно. Все работает, все связано. Даже статус устройств показывает правильно. Но при смене состояния в логах эта же ошибка. Будет фикс?

**Comment by shalasashka** [comment]
> Тоже все активно. Все работает, все связано. Даже статус устройств показывает правильно. Но при смене состояния в логах эта же ошибка. Будет фикс?

По совету тоже накатил Node-Red. Есть интеграции с Homebridge, z2m, алисой и телеграмом. Правда ноды функций еще не осилил, поэтому на скрине немного беспорядок
![image](https://user-images.githubusercontent.com/1362408/212272137-c2db51bd-8bda-4d78-94c9-4c8a8a47284b.png)

**Comment by RFG-G** [comment]
Исправлено в #17

**Comment by dobriybober** [comment]
> Исправлено в #17

А npmку можете исправить пожалуйста, чтобы обновить плагин в homebridge автоматом?
