### ISSUE TITLE
В Алисе не появляются устройство AppleTv

### ISSUE THREAD

**Issue by svaganov** [G-On-dev/homebridge-g-on-alice#28]
Установил Homebridge и плагин G-ON. Все обновлено до последней версии. Добавил мост в "Дом" на устройстве Apple TV. 
После этого пытаюсь найти устройство AppleTV на своем устройстве с Яндекс Алиса. но Алиса пишет, что G-On Homebridge новых устройств нет. 

2023-09-21T21:46:33.795Z hapNodeJSClient Homebridge instance discovered Homebridge B897 BD68 @ http://192.168.0.192:51558 with 1 accessories
2023-09-21T21:46:52.757Z hapNodeJSClient Ready
[9/22/2023, 12:46:52 AM] [G-On Alice] ERROR: HAP Discovery failed, please review config

Вот конфиг:
```
{
    "bridge": {
        "name": "Homebridge B897",
        "username": "0E:CE:04:2D:D4:5B",
        "port": 51558,
        "pin": "183-00-683",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "G-On Alice",
            "username": "Пользователь",
            "password": "Пароль",
            "pin": "номер пин",
            "debug": true,
            "platform": "G-On Alice"
        },
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}
```
Что-то не доделал?

**Comment by NilsBohr** [comment]
Homebridge не умеет работать с Apple Homepod или Apple TV как с конечными устройствами.

Его функционал наоборот - прокидывать не Apple Homekit устройства в Apple Home.
Соответственно и плагин для Алисы работает только с теми устройствами что видны Homebridge

Поэтому и устройства не видны.
Посоветовать ничего не могу, надо смотреть в сторону каких то сторонних плагинов или вообще Home Assistant

**Comment by svaganov** [comment]
Никита, здравствуйте. Большое спасибо за информацию.

пн, 25 сент. 2023 г., 10:47 Nikita Selednikov ***@***.***>:
