### ISSUE TITLE
Перестала работать

### ISSUE THREAD

**Issue by kot-925** [G-On-dev/homebridge-g-on-alice#3]
Ничего не делал, просто в один момент Алиса перестала выполнять команды
ERROR: ( homebridge-g-on-alice) You have an issue with your installation, please review the README.

**Comment by Ziracul** [comment]
пин добавьте

**Comment by kot-925** [comment]
Он у меня был добавлен. После последнего обновления на v0.1.5 все заработало, благодарю!
