### ISSUE TITLE
ни одного устройства

### ISSUE THREAD

**Issue by stalkerj** [G-On-dev/homebridge-g-on-alice#4]
После установки и настройки плагина не появилось ни одного устройства из Хомбриджа.
Вот что пишет в логах

[8/11/2019, 2:47:47 PM] [G-On Alice] ERROR: HAP Discovery failed, please review config
2019-08-11T11:47:50.412Z hapNodeJSClient HAP Discover failed Homebridge http://undefined:51826 error ENOTFOUND
2019-08-11T11:48:03.929Z hapNodeJSClient HAP Discover failed v koridore http://169.254.151.223:38093 error EHOSTUNREACH
2019-08-11T11:48:03.931Z hapNodeJSClient HAP Discover failed parking http://169.254.151.223:35523 error EHOSTUNREACH
2019-08-11T11:48:03.932Z hapNodeJSClient HAP Discover failed NODE-RED Bridge http://169.254.151.223:33803 error EHOSTUNREACH
2019-08-11T11:48:03.933Z hapNodeJSClient HAP Discover failed homebridge http://169.254.151.223:51826 error EHOSTUNREACH

**Comment by stalkerj** [comment]
На другом хаб вот такую ошибку выдает в логах

homebridge : TTY=pts/0 ; PWD=/var/lib/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge
pam_unix(sudo:session): session opened for user root by (uid=0)
[2019-8-11 19:15:59] [G-On Alice] ERROR: No connection to homebridge.g-on.io. Retrying... please review the README and the Homebridge configuration.

**Comment by G-On-dev** [comment]
> [8/11/2019, 2:47:47 PM] [G-On Alice] ERROR: HAP Discovery failed, please review config
> 2019-08-11T11:47:50.412Z hapNodeJSClient HAP Discover failed Homebridge http://undefined:51826 error ENOTFOUND
> 2019-08-11T11:48:03.929Z hapNodeJSClient HAP Discover failed v koridore http://169.254.151.223:38093 error EHOSTUNREACH
> 2019-08-11T11:48:03.931Z hapNodeJSClient HAP Discover failed parking http://169.254.151.223:35523 error EHOSTUNREACH
> 2019-08-11T11:48:03.932Z hapNodeJSClient HAP Discover failed NODE-RED Bridge http://169.254.151.223:33803 error EHOSTUNREACH
> 2019-08-11T11:48:03.933Z hapNodeJSClient HAP Discover failed homebridge http://169.254.151.223:51826 error EHOSTUNREACH

Такое ощущение что у вас много разных Homebridge в сети, и плагин пытается до всех по очереди достучаться.
Проверьте, указан ли пин код правильно для хотя бы одного из них.
Также надо чтобы Homebridge был запущен в небезопасном режиме (опция `-I`)


> На другом хаб вот такую ошибку выдает в логах
> 
> homebridge : TTY=pts/0 ; PWD=/var/lib/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge
> pam_unix(sudo:session): session opened for user root by (uid=0)
> [2019-8-11 19:15:59] [G-On Alice] ERROR: No connection to homebridge.g-on.io. Retrying... please review the README and the Homebridge configuration.

Очень странно, сервер не падал и работает стабильно. Есть ли подключение к интернету? Правильно ли указан логин и пароль от homebridge.g-on.io?

**Comment by stalkerj** [comment]
> > [8/11/2019, 2:47:47 PM] [G-On Alice] ERROR: HAP Discovery failed, please review config
> > 2019-08-11T11:47:50.412Z hapNodeJSClient HAP Discover failed Homebridge http://undefined:51826 error ENOTFOUND
> > 2019-08-11T11:48:03.929Z hapNodeJSClient HAP Discover failed v koridore http://169.254.151.223:38093 error EHOSTUNREACH
> > 2019-08-11T11:48:03.931Z hapNodeJSClient HAP Discover failed parking http://169.254.151.223:35523 error EHOSTUNREACH
> > 2019-08-11T11:48:03.932Z hapNodeJSClient HAP Discover failed NODE-RED Bridge http://169.254.151.223:33803 error EHOSTUNREACH
> > 2019-08-11T11:48:03.933Z hapNodeJSClient HAP Discover failed homebridge http://169.254.151.223:51826 error EHOSTUNREACH
> 
> Такое ощущение что у вас много разных Homebridge в сети, и плагин пытается до всех по очереди достучаться.
> Проверьте, указан ли пин код правильно для хотя бы одного из них.
> Также надо чтобы Homebridge был запущен в небезопасном режиме (опция `-I`)
> 
> > На другом хаб вот такую ошибку выдает в логах
> > homebridge : TTY=pts/0 ; PWD=/var/lib/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge
> > pam_unix(sudo:session): session opened for user root by (uid=0)
> > [2019-8-11 19:15:59] [G-On Alice] ERROR: No connection to homebridge.g-on.io. Retrying... please review the README and the Homebridge configuration.
> 
> Очень странно, сервер не падал и работает стабильно. Есть ли подключение к интернету? Правильно ли указан логин и пароль от homebridge.g-on.io?

У меня сейчас 3 Homebridge в сети (про ограничения в кол-ве мостов у вас нет указаний в описании). Но плагин установлен только на одном. Последняя ошибка появляется на Вашем Хабе. Данные указаны верно.

**Comment by stalkerj** [comment]
Была ошибка в пароле. Вторая проблема ушла.
Первая проблема тоже решилась, после включения небезопасного режима и добавления строчки с пином в конфиг.

**Comment by stalkerj** [comment]
Часть проблем решилась.
Осталось только проверить работу с несколькими мостами одновременно

Отправлено с iPhone

**Comment by stalkerj** [comment]
На нескольких мостах одновременно тоже все работает. Хотелось бы увидеть не только термостат, но и кондиционер, так как термостат только включает кондей, но регулировать ничего не дает.

**Comment by stalkerj** [comment]
Устройства из Homebridge работают, управляются, но при этом в логах бриджа есть ошибка, появляется каждые несколько секунд

[8/12/2019, 1:16:59 PM] [G-On Alice] ERROR: No connection to homebridge.g-on.io. Retrying... please review the README and the Homebridge configuration.

**Comment by stalkerj** [comment]
Я пока лучше в гитхабе буду писать о проблеме, чтобы те, кто столкнется так же видели решение

Отправлено с iPhone

**Comment by G-On-dev** [comment]
Рад слышать что проблемы решились и устройства появились.

> На нескольких мостах одновременно тоже все работает. Хотелось бы увидеть не только термостат, но и кондиционер, так как термостат только включает кондей, но регулировать ничего не дает.

> Устройства из Homebridge работают, управляются, но при этом в логах бриджа есть ошибка, появляется каждые несколько секунд
> 
> [8/12/2019, 1:16:59 PM] [G-On Alice] ERROR: No connection to homebridge.g-on.io. Retrying... please review the README and the Homebridge configuration.

> Я пока лучше в гитхабе буду писать о проблеме, чтобы те, кто столкнется так же видели решение Отправлено с iPhone

Раз уж вы пишите в гитхаб, давайте следовать принятым нормам. Одна проблема, одна issue. Пожалуйста опишите вашу проблему с кондиционеров в отдельной issue. Пока что смутно представляю о чем речь.

**Comment by vitaliy-kozlov** [comment]
[G-On Alice] ERROR: No connection to homebridge.g-on.io. Retrying... please review the README and the Homebridge configuration. - таже проблема, пробовал переустанавливать

**Comment by katgies** [comment]
Привет, а помогите, пожалуйста, с проблемой: 
[1/4/2024, 11:39:52 AM] [G-On Alice] ERROR: HAP Discovery failed, please review config

пароль верный, пин прописан, небезопасный режим включен
в чем еще могут быть проблемы?
